/*This query is used to identify all weenie_properties_create_list wcids that are assigned
to a particular wcid.  ie. what items a chest contains,items a vendor has in shop,items a creature has for treasure, etc */

SELECT
  w1.class_Id AS query_wcid
 , w1.`class_Name` AS query_wcid_name
 ,w1.`type` AS query_wcid_type
 , CASE w1.`type`
	WHEN 0 THEN "Undef"
	WHEN 1 THEN "Generic"
	WHEN 2 THEN "Clothing"
	WHEN 3 THEN "MissileLauncher"
	WHEN 4 THEN "Missile"
	WHEN 5 THEN "Ammunition"
	WHEN 6 THEN "MeleeWeapon"
	WHEN 7 THEN "Portal"
	WHEN 8 THEN "Book"
	WHEN 9 THEN "Coin"
	WHEN 10 THEN "Creature"
	WHEN 11 THEN "Admin"
	WHEN 12 THEN "Vendor"
	WHEN 13 THEN "HotSpot"
	WHEN 14 THEN "Corpse"
	WHEN 15 THEN "Cow"
	WHEN 16 THEN "AI"
	WHEN 17 THEN "Machine"
	WHEN 18 THEN "Food"
	WHEN 19 THEN "Door"
	WHEN 20 THEN "Chest"
	WHEN 21 THEN "Container"
	WHEN 22 THEN "Key"
	WHEN 23 THEN "Lockpick"
	WHEN 24 THEN "PressurePlate"
	WHEN 25 THEN "LifeStone"
	WHEN 26 THEN "Switch"
	WHEN 27 THEN "PKModifier"
	WHEN 28 THEN "Healer"
	WHEN 29 THEN "LightSource"
	WHEN 30 THEN "Allegiance"
	WHEN 31 THEN "UNKNOWN__GUESSEDNAME32"
	WHEN 32 THEN "SpellComponent"
	WHEN 33 THEN "ProjectileSpell"
	WHEN 34 THEN "Scroll"
	WHEN 35 THEN "Caster"
	WHEN 36 THEN "Channel"
	WHEN 37 THEN "ManaStone"
	WHEN 38 THEN "Gem"
	WHEN 39 THEN "AdvocateFane"
	WHEN 40 THEN "AdvocateItem"
	WHEN 41 THEN "Sentinel"
	WHEN 42 THEN "GSpellEconomy"
	WHEN 43 THEN "LSpellEconomy"
	WHEN 44 THEN "CraftTool"
	WHEN 45 THEN "LScoreKeeper"
	WHEN 46 THEN "GScoreKeeper"
	WHEN 47 THEN "GScoreGatherer"
	WHEN 48 THEN "ScoreBook"
	WHEN 49 THEN "EventCoordinator"
	WHEN 50 THEN "Entity"
	WHEN 51 THEN "Stackable"
	WHEN 52 THEN "HUD"
	WHEN 53 THEN "House"
	WHEN 54 THEN "Deed"
	WHEN 55 THEN "SlumLord"
	WHEN 56 THEN "Hook"
	WHEN 57 THEN "Storage"
	WHEN 58 THEN "BootSpot"
	WHEN 59 THEN "HousePortal"
	WHEN 60 THEN "Game"
	WHEN 61 THEN "GamePiece"
	WHEN 62 THEN "SkillAlterationDevice"
	WHEN 63 THEN "AttributeTransferDevice"
	WHEN 64 THEN "Hooker"
	WHEN 65 THEN "AllegianceBindstone"
	WHEN 66 THEN "InGameStatKeeper"
	WHEN 67 THEN "AugmentationDevice"
	WHEN 68 THEN "SocialManager"
	WHEN 69 THEN "Pet"
	WHEN 70 THEN "PetDevice"
	WHEN 71 THEN "CombatPet"
   END AS query_wcid_type_name
 , w2.`class_Id` AS item_assigned_wcid
 , w2.`class_Name` AS item_assigned_name
 , w2.`type` AS item_assigned_type
 , CASE w2.`type`
	WHEN 0 THEN "Undef"
	WHEN 1 THEN "Generic"
	WHEN 2 THEN "Clothing"
	WHEN 3 THEN "MissileLauncher"
	WHEN 4 THEN "Missile"
	WHEN 5 THEN "Ammunition"
	WHEN 6 THEN "MeleeWeapon"
	WHEN 7 THEN "Portal"
	WHEN 8 THEN "Book"
	WHEN 9 THEN "Coin"
	WHEN 10 THEN "Creature"
	WHEN 11 THEN "Admin"
	WHEN 12 THEN "Vendor"
	WHEN 13 THEN "HotSpot"
	WHEN 14 THEN "Corpse"
	WHEN 15 THEN "Cow"
	WHEN 16 THEN "AI"
	WHEN 17 THEN "Machine"
	WHEN 18 THEN "Food"
	WHEN 19 THEN "Door"
	WHEN 20 THEN "Chest"
	WHEN 21 THEN "Container"
	WHEN 22 THEN "Key"
	WHEN 23 THEN "Lockpick"
	WHEN 24 THEN "PressurePlate"
	WHEN 25 THEN "LifeStone"
	WHEN 26 THEN "Switch"
	WHEN 27 THEN "PKModifier"
	WHEN 28 THEN "Healer"
	WHEN 29 THEN "LightSource"
	WHEN 30 THEN "Allegiance"
	WHEN 31 THEN "UNKNOWN__GUESSEDNAME32"
	WHEN 32 THEN "SpellComponent"
	WHEN 33 THEN "ProjectileSpell"
	WHEN 34 THEN "Scroll"
	WHEN 35 THEN "Caster"
	WHEN 36 THEN "Channel"
	WHEN 37 THEN "ManaStone"
	WHEN 38 THEN "Gem"
	WHEN 39 THEN "AdvocateFane"
	WHEN 40 THEN "AdvocateItem"
	WHEN 41 THEN "Sentinel"
	WHEN 42 THEN "GSpellEconomy"
	WHEN 43 THEN "LSpellEconomy"
	WHEN 44 THEN "CraftTool"
	WHEN 45 THEN "LScoreKeeper"
	WHEN 46 THEN "GScoreKeeper"
	WHEN 47 THEN "GScoreGatherer"
	WHEN 48 THEN "ScoreBook"
	WHEN 49 THEN "EventCoordinator"
	WHEN 50 THEN "Entity"
	WHEN 51 THEN "Stackable"
	WHEN 52 THEN "HUD"
	WHEN 53 THEN "House"
	WHEN 54 THEN "Deed"
	WHEN 55 THEN "SlumLord"
	WHEN 56 THEN "Hook"
	WHEN 57 THEN "Storage"
	WHEN 58 THEN "BootSpot"
	WHEN 59 THEN "HousePortal"
	WHEN 60 THEN "Game"
	WHEN 61 THEN "GamePiece"
	WHEN 62 THEN "SkillAlterationDevice"
	WHEN 63 THEN "AttributeTransferDevice"
	WHEN 64 THEN "Hooker"
	WHEN 65 THEN "AllegianceBindstone"
	WHEN 66 THEN "InGameStatKeeper"
	WHEN 67 THEN "AugmentationDevice"
	WHEN 68 THEN "SocialManager"
	WHEN 69 THEN "Pet"
	WHEN 70 THEN "PetDevice"
	WHEN 71 THEN "CombatPet"
   END AS item_type_name
 , wp.`destination_Type`
 , CASE wp.`destination_Type`
	WHEN 0 THEN "Undef"
	WHEN 1 THEN "Contain"
	WHEN 2 THEN "Wield"
	WHEN 4 THEN "Shop"
	WHEN 7 THEN "Checkpoint"
	WHEN 8 THEN "Treasure"
	WHEN 9 THEN "Contain Treasure"
	WHEN 10 THEN "Wield Treasure"
	WHEN 12 THEN "Shop Treasure"
	WHEN 16 THEN "House Buy"
	WHEN 32 THEN "House Rent"
  END AS destination
FROM
  weenie_properties_create_list AS wp
   INNER JOIN weenie AS w1
    ON (wp.object_Id = w1.class_Id)
  INNER JOIN weenie AS `w2`
    ON (w2.class_Id = wp.weenie_Class_Id)
 WHERE wp.object_Id= 9000001; /*Replace with the WCID you are inquring about*/
